// Runs the MCP stdio tools against one owned WinUAE at a time.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import {pathToFileURL} from 'node:url';
const {WINUAE_PATH, WINUAE_ROM, WINUAE_MCP_PATH} = process.env;
assert(WINUAE_PATH && WINUAE_ROM && WINUAE_MCP_PATH, 'Set WINUAE_PATH, WINUAE_ROM and WINUAE_MCP_PATH');
const sdk = path.resolve(WINUAE_MCP_PATH, 'node_modules/@modelcontextprotocol/sdk/dist/esm/client');
const {Client} = await import(pathToFileURL(path.join(sdk, 'index.js')));
const {StdioClientTransport} = await import(pathToFileURL(path.join(sdk, 'stdio.js')));
const reserve = net.createServer();
await new Promise((resolve, reject) => { reserve.once('error', reject); reserve.listen(0, '127.0.0.1', resolve); });
const port = reserve.address().port;
await new Promise(resolve => reserve.close(resolve));
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'winuae-mcp-smoke-'));
console.log('Test files:', temp);
const config = path.join(temp, 'machine.uae');
const screenshot = path.join(temp, 'screen shot.png');
fs.writeFileSync(config,`boot_rom_uae=full\nuse_gui=no\ncpu_model=68000\ncpu_compatible=true\nchipmem_size=2\ncachesize=0\nkickstart_rom_file=${WINUAE_ROM}\n`);
const original=fs.readFileSync(config);
const transport=new StdioClientTransport({command:process.execPath,args:[path.resolve(WINUAE_MCP_PATH, 'dist/index.js')],env:{...process.env,WINUAE_PATH,WINUAE_CONFIG:config,WINUAE_GDB_PORT:String(port),SDL_VIDEODRIVER:'dummy',SDL_AUDIODRIVER:'dummy',QT_QPA_PLATFORM:'offscreen'},stderr:'pipe'});
const client=new Client({name:'winuae-integration-test',version:'1'},{capabilities:{}});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function call(name,args={}){const r=await client.callTool({name,arguments:args});const text=r.content.map(c=>c.text||'').join('\n');assert(!text.startsWith('Error:') && !/VERIFY (FAILED|MISMATCH)/.test(text),name+': '+text);console.log(name+': '+text.slice(0,120));return text;}
try {
 await client.connect(transport);
 transport.stderr?.on('data',d=>fs.appendFileSync(path.join(temp, 'mcp.log'),d));
 await call('winuae_connect');await call('winuae_continue');await delay(1500);
 await call('winuae_input',{action:'key',code:0x45,pressed:true});
 assert.equal(JSON.parse(await call('winuae_input',{action:'status'})).held.length,1);
 // Input/status must not turn a running target into a debugger stop.
 const waiting=await client.callTool({name:'winuae_wait_stop',arguments:{timeout_ms:30}});
 assert(waiting.isError);assert.match(waiting.content[0].text,/timed out/i);
 assert.deepEqual(JSON.parse(await call('winuae_input',{action:'release'})).held,[]);
 await call('winuae_pause');
 // Read the actual active-low mouse/fire line with guest instructions.
 await call('winuae_memory_write',{address:'$10000',data:'103900bfe00160f8'});
 await call('winuae_registers_set',{SR:'$2700',A7:'$30000',PC:'$10000'});
 await call('winuae_input',{action:'button',port:0,button:0,pressed:true});
 await call('winuae_step',{count:1});
 const pressed=JSON.parse(await call('winuae_snapshot')).registers.D0;
 await call('winuae_input',{action:'release'});
 await call('winuae_registers_set',{PC:'$10000'});await call('winuae_step',{count:1});
 const released=JSON.parse(await call('winuae_snapshot')).registers.D0;
 assert.equal(pressed & 0x40,0);assert.equal(released & 0x40,0x40);
 // A guest loop observes both edges of a frame-timed button tap.
 await call('winuae_memory_write',{address:'$10000',data:'103900bfe0010800000666f413c000026000103900bfe0010800000667f413c00002600160fe'});
 await call('winuae_memory_write',{address:'$26000',data:'ffff'});
 await call('winuae_registers_set',{PC:'$10000'});
 await call('winuae_breakpoint_set',{address:'$10024'});
 await call('winuae_input_sequence',{steps:[{action:'button',button:0,pressed:true,after_frames:2},{action:'button',button:0,pressed:false,after_frames:5}]});
 await delay(40);
 assert.equal(JSON.parse(await call('winuae_input',{action:'status'})).sequence.next,0);
 await call('winuae_continue');await call('winuae_wait_stop',{timeout_ms:3000});
 assert.equal(JSON.parse(await call('winuae_input',{action:'status'})).sequence.state,'completed');
 const edges=await call('winuae_memory_read',{address:'$26000',length:2});
 const edgeBytes=edges.split('\n').pop().trim().split(/\s+/).map(b=>parseInt(b,16));
 assert.equal(edgeBytes[0] & 0x40,0);assert.equal(edgeBytes[1] & 0x40,0x40);
 await call('winuae_breakpoint_clear',{address:'$10024'});
 await call('winuae_key_tap',{codes:[0x60,0x20],hold_frames:120,resume:true});
 await delay(60);
 assert.equal(JSON.parse(await call('winuae_input',{action:'status'})).held.length,2);
 const cancelled=JSON.parse(await call('winuae_input',{action:'release'}));
 assert.equal(cancelled.sequence.state,'cancelled');assert.deepEqual(cancelled.held,[]);
 await call('winuae_pause');

 await call('winuae_memory_write',{address:'$10000',data:'700152804e7160fe'});
 await call('winuae_registers_set',{SR:'$2700',A7:'$30000',PC:'$10000'});
 await call('winuae_range_step',{start:'$10000',end:'$10004'});
 await delay(100); await call('winuae_pause');
 assert.match(await call('winuae_registers_get'),/PC=\$00010004/);
 await call('winuae_registers_set',{PC:'$10000'});
 await call('winuae_step',{count:2});
 await call('winuae_memory_read',{address:'$10000',length:8});
 await call('winuae_memory_dump',{address:'$10000',length:8});
 await call('winuae_custom_registers');
 assert.match(await call('winuae_disassemble',{address:'$10000',count:3}), /moveq/i);
 await call('winuae_screenshot',{filename:screenshot});
 const png=fs.readFileSync(screenshot);assert.equal(png.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
 assert.equal(JSON.parse(await call('winuae_process_breakpoint', {action:'set',name:'Fixture'})).armed,true);
 assert.equal(JSON.parse(await call('winuae_process_breakpoint', {action:'status'})).name,'Fixture');
 assert.equal(JSON.parse(await call('winuae_process_breakpoint', {action:'clear'})).armed,false);
 const ram = Buffer.alloc(0x310);
 ram[8] = 13; ram.writeUInt32BE(0x20200, 10);
 ram.writeUInt32BE(0x20100 / 4, 172);
 ram.writeUInt32BE(0x20220 / 4, 0x100 + 16);
 ram.writeUInt32BE(0x20300 / 4, 0x100 + 60);
 ram.write('Fixture', 0x200); ram[0x220] = 7; ram.write('Fixture', 0x221);
 ram.writeUInt32BE(16, 0x2fc);
 await call('winuae_memory_write',{address:'$20000',data:ram.toString('hex')});
 const segments=JSON.parse(await call('winuae_loaded_segments',{address:'$20000'}));
 assert.deepEqual(segments.segments,[{index:0,address:0x20304,size:8}]);
 assert.equal(JSON.parse(await call('winuae_exceptions',{action:'set',vectors:[4]})).mask,'0000000000000010');
 await call('winuae_memory_write',{address:'$10',data:'00010100'});
 await call('winuae_memory_write',{address:'$10000',data:'4afc'});
 await call('winuae_memory_write',{address:'$10100',data:'60fe'});
 await call('winuae_registers_set',{SR:'$2700',A7:'$30000',PC:'$10000'});
 await call('winuae_continue'); await delay(100);
 assert.match(await call('winuae_pause'),/winuae-exception:04/);
 assert.equal(JSON.parse(await call('winuae_exceptions',{action:'status'})).last.instruction_pc,0x10000);
 await call('winuae_exceptions',{action:'clear'});
 const dma=JSON.parse(await call('winuae_dma_watchpoint',{action:'add',address:'$25000',length:8,mode:'read',sources:['copper']}));
 assert.equal(JSON.parse(await call('winuae_dma_watchpoint',{action:'list'}))[0].mask,0x200);
 assert.deepEqual(JSON.parse(await call('winuae_dma_watchpoint',{action:'remove',id:dma.id})),[]);
 await call('winuae_guest_output',{action:'on'});
 await call('winuae_memory_write',{address:'$26000',data:Buffer.from('MCP guest output\0').toString('hex')});
 await call('winuae_memory_write',{address:'$10000',data:'487900026000487800564eb900f0ff60508f60fe'});
 await call('winuae_registers_set',{PC:'$10000'});
 await call('winuae_breakpoint_set',{address:'$10012'});
 await call('winuae_continue');await delay(100);await call('winuae_pause');
 assert.equal(JSON.parse(await call('winuae_guest_output',{action:'read'})).records[0].text,'MCP guest output');
 await call('winuae_breakpoint_clear',{address:'$10012'});
 await call('winuae_guest_output',{action:'off'});
 assert.deepEqual(JSON.parse(await call('winuae_guest_output',{action:'clear'})).records,[]);
 const checkpoint=path.join(temp,'MCP checkpoint.uss');
 await call('winuae_registers_set',{D0:123,PC:'$10000'});
 await call('winuae_checkpoint',{action:'save',file:checkpoint});
 await call('winuae_registers_set',{D0:456,PC:'$10004'});
 const restored=JSON.parse(await call('winuae_checkpoint',{action:'restore',file:checkpoint}));
 assert.equal(restored.registers.D0,123);assert.equal(restored.registers.PC,0x10000);
 await call('winuae_status');
 await call('winuae_reset');
 await call('winuae_eject_disk',{drive:0});
 await call('winuae_disconnect');
 await call('winuae_connect');await call('winuae_disconnect');
 assert.deepEqual(fs.readFileSync(config),original);
 console.log('MCP stdio end-to-end passed; user config unchanged; child shutdown awaited');
}finally{try{await call('winuae_disconnect');}catch{}await client.close();}
